### ISSUE TITLE
PATH="/tmp"

### ISSUE THREAD

**Issue by nilminus** [NullArray/RootHelper#1]
Line 43: PATH="/tmp/" , changes the PATH looking for binaries.
Subsequently, wget and the other binaries won't be found and execute.

What is the point of this line if I may ask? (I assume you originally wanted to dynamically change the destination path at some point)
I apologise in advance in case I am missing something.

**Comment by NullArray** [comment]
Thank you for mentioning this. The point of the line was to store the /tmp/ directory to a variable for the cleanup operation at line 72.

```
find $PATH/* -exec rm {} \
```

I've changed it to "$dir" which should resolve the issue.

https://github.com/NullArray/RootHelper/commit/de3d2ece93910410d5afbdea16c4c5ce05593e3c

Just a semantic error on my part.  Anything else? I'd like to resolve as much as possible before closing the issue, if there is more.

**Comment by NullArray** [comment]
Alright.
