### ISSUE TITLE
b

### ISSUE THREAD

**Issue by ghost** [NullArray/RootHelper#10]

**Comment by Dragoncodedestroyer** [comment]
![image](https://user-images.githubusercontent.com/107947907/174868935-675c70d7-52f9-4dc3-95d9-0d808b2d0132.png)

**Comment by Dragoncodedestroyer** [comment]
![image](https://user-images.githubusercontent.com/107947907/174869074-29f019ab-5520-4358-9061-98cc62840434.png)
