### ISSUE TITLE
Q2w2

### ISSUE THREAD

**Issue by 2karuitach** [NullArray/RootHelper#2]
#include <iostream>
using namespace std;

int main()
{
	cout<<"Hello World";

	return 0;
}
#include <iostream>
#include <cmath>
using namespace std;
 
int main ()
{
 
    //variable declaration
    int number;
 
    //take input for number from user
    cout<<"Enter number : ";
    cin>>number;
 
    //use of sqrt function to find square root
    cout << "square root of " << number << " is " << sqrt(number);
 
    cout<<"\n\n";
 
    //use of cbrt function to find cube root
    cout << "cube root of " << number << " is " << cbrt(number);
 
    cout<<"\n";
#include<iostream>
using namespace std;
 
int main()
{
  int num;
  cout<<"Enter any non-zero Number : ";
  cin>>num;
  if(num>0)
    {
        cout<<"Number is positive";
    }
  else
    {
        cout<<"Number is negative";
    }
 
  return 0;
}
}
#include<iostream>

using namespace std;

 

int main()

{

  int num;

  cout<<"Enter any non-zero Number : ";

  cin>>num;

  if(num>0)

    {

        cout<<"Number is positive";

    }

  else

    {

        cout<<"Number is negative";

    }

 

  return 0;

}

OUTPUT

Enter any non-zero Number : -9 Number is negative
#include <iostream>
using namespace std;
 
int main()
{
    //variable declaration
    char asciichar;
 
    //take user input
    cout << "Enter a character : ";
    cin >> asciichar;
 
    //display ascii value of character
    cout << "\nIt's ascii  value is : " << (int) asciichar << endl;
 
    return 0;
}
#include <iostream>

 

using namespace std;

 

int main ()

{

   int  var;

   char var_array[10];

 

   cout << "Address of variable1 is : ";

   cout << &var << "\n";

 

   cout << "Address of variable2 is : ";

   cout << &var_array<< "\n";

 

   return 0;

}

OUTPUT

Address of variable1 is : 0x29feec Address of variable2 is : 0x29fee2

#include <iostream>
using namespace std;
int main ( )
 {
    int num;
    num = 50;
 
    cout<<"number is="<<num<<endl;
    //endl is manipulator
    //endl is output manipulator
    cout<<"value of number="<<num<<"\n";
 }
#include<iostream>
using namespace std;
 
int main ()
{
   // Local variable declaration:
   int num = 10;
 
   // do loop execution
   do
   {
       cout << "value of number: " << num << endl;
       num=num+ 1;
       if( num > 15)
       {
          // terminate the loop
          break;
       }
   }while( num < 20 );
 
   return 0;
}
//program to show how exception handling work
 
#include <iostream>
using namespace std;
 
//method definition
double divisionby(int num1, int num2)
{
    if( num2 == 0 )
    {
        throw "Division by zero condition!";
    }
    cout<<"answer = ";
    return (num1/num2);
}
 
int main ()
{
    //variable declaration
    int n1,n2;
 
    //take user input
    cout<<"enter two numbers for division operation  :  ";
    cin>>n1>>n2;
    double n3 = 0;
 
    //try catch to handle run time error
    try
    {
        n3 = divisionby(n1, n2);
        cout << n3 << endl;
    }
    catch (const char* msg)
    {
        //it will display error msg
        cout << msg << endl;
    }
 
   return 0;
}
//id-16776
#include <iostream>
using namespace std;
 
double divisionby(int num1, int num2)
{
   if( num2 == 0 )
   {
      throw "Division by zero condition!";
   }
   cout<<"answer = ";
   return (num1/num2);
}
 
int main ()
{
   int n1,n2;
   cout<<"enter two numbers for division operation  :  ";
   cin>>n1>>n2;
   double n3 = 0;
 
//try catch to handle run time error
    try
       {
         n3 = divisionby(n1, n2);
         cout << n3 << endl;
       }
    catch (const char* msg)
        {
            //it will display error msg
         cout << msg << endl;
        }
 
   return 0;
}
#include<iostream>

#include<conio.h>

#include<iomanip>

#include<stdlib.h>

#include<ctype.h>

#include<fstream>

using namespace std;

 

int main( )

{

    //variable declaration

  ofstream outfile;

  ifstream  infile;

  char fname1[10],fname2[20];

  char ch,uch;

 

    //user Input

  cout<<"Enter a file name to be copied ";

  cin>> fname1;

  cout<<"Enter new file name";

  cin>>fname2;

  infile.open(fname1);

 

    if( infile.fail( ) )

        {

            cerr<< " No such a file Exit";

            getch();

            exit(1);

        }

  outfile.open( fname2);

    if(outfile.fail( ))

    {

      cerr<<"Unable to create a file";

      getch();

      exit(1);

    }

  while( !infile.eof( ) )

  {

    ch = (char) infile.get( );

    uch = toupper(ch);

    outfile.put(uch);

  }

  infile.close( );

  outfile.close( );

 

}

OUTPUT

Enter a file name to be copied : old.txt Enter new file name : new.txt

#include <iostream>

#include <cmath>

using namespace std;

 

int main ()

{

 

    //variable declaration

    int number;

 

    //take input for number from user

    cout<<"Enter number : ";

    cin>>number;

 

    //use of sqrt function to find square root

    cout << "square root of " << number << " is " << sqrt(number);

 

    cout<<"\n\n";

 

    //use of cbrt function to find cube root

    cout << "cube root of " << number << " is " << cbrt(number);

 

    cout<<"\n";

}

OUTPUT

Enter number : 27 square root of 27 is 5.19615 cube root of 27 is 3
#include <iostream>
#include <cmath>
using namespace std;
 
int main ()
{
 
    //variable declaration
    int number;
 
    //take input for number from user
    cout<<"Enter number : ";
    cin>>number;
 
    //use of sqrt function to find square root
    cout << "square root of " << number << " is " << sqrt(number);
 
    cout<<"\n\n";
 
    //use of cbrt function to find cube root
    cout << "cube root of " << number << " is " << cbrt(number);
 
    cout<<"\n";
}
#include <stdio.h>
#include <math.h>
#include<iostream>
 
using namespace std;
 
int main()
{
    int num, tempnum;
 
    cout<<"Enter a number: ";
    cin>>num;
 
    tempnum = sqrt(num);
 
    if(tempnum*tempnum==num)
    {
       cout<<"YES,its perfect square of : "<<sqrt(num);
    }
 
    else
    {
        cout<<"NO,its not perfect square";
    }
 
    return 0;
}

#include <iostream>
#include <vector>
 
using namespace std;
 
int main()
{
    //Vector to store integers
    vector <int> vex;
    cout<<"added value in vector  :\n";
 
    //add value in vector
    vex.push_back(130);
    vex.push_back(500);
    vex.push_back(353);
 
    for(int x=0; x<vex.size(); x++)
        {
            //Should output 130 500 353
            cout<<vex[x]<<" ";
        }
 
    //Checks if empty
    if(!vex.empty())
        {
            //Clears vector
            vex.clear();
        }
 
    vector <int> another_vector;
    another_vector.push_back(10);
    vex.push_back(10);
 
    if(vex==another_vector)
        {
            vex.push_back(20);
        }
 
    for(int y=0; y<vex.size(); y++)
        {
            //Should output 10 20
            cout<<vex[y]<<" ";
        }
    return 0;
}

**Comment by NullArray** [comment]
Please use the issues section for the purposes it is intended to. If you have a question please feel free to ask. Just pasting random code doesn't help anyone.

**Comment by 2karuitach** [comment]
#include 
using namespace std;

int main()
{
cout<<"Hello World";

return 0;
}
#include 
#include 
using namespace std;
 
int main ()
{
 
    //variable declaration
    int number;
 
    //take input for number from user
    cout<<"Enter number : ";
    cin>>number;
 
    //use of sqrt function to find square root
    cout << "square root of " << number << " is " << sqrt(number);
 
    cout<<"\n\n";
 
    //use of cbrt function to find cube root
    cout << "cube root of " << number << " is " << cbrt(number);
 
    cout<<"\n";
#include
using namespace std;
 
int main()
{
  int num;
  cout<<"Enter any non-zero Number : ";
  cin>>num;
  if(num>0)
    {
        cout<<"Number is positive";
    }
  else
    {
        cout<<"Number is negative";
    }
 
  return 0;
}
}
#include

using namespace std;

 

int main()

{

  int num;

  cout<<"Enter any non-zero Number : ";

  cin>>num;

  if(num>0)

    {

        cout<<"Number is positive";

    }

  else

    {

        cout<<"Number is negative";

    }

 

  return 0;

}

OUTPUT

Enter any non-zero Number : -9 Number is negative
#include 
using namespace std;
 
int main()
{
    //variable declaration
    char asciichar;
 
    //take user input
    cout << "Enter a character : ";
    cin >> asciichar;
 
    //display ascii value of character
    cout << "\nIt's ascii  value is : " << (int) asciichar << endl;
 
    return 0;
}
#include

 

using namespace std;

 

int main ()

{

   int  var;

   char var_array[10];

 

   cout << "Address of variable1 is : ";

   cout << &var << "\n";

 

   cout << "Address of variable2 is : ";

   cout << &var_array<< "\n";

 

   return 0;

}

OUTPUT

Address of variable1 is : 0x29feec Address of variable2 is : 0x29fee2

#include 
using namespace std;
int main ( )
 {
    int num;
    num = 50;
 
    cout<<"number is="<<num<<endl;
    //endl is manipulator
    //endl is output manipulator
    cout<<"value of number="<<num<<"\n";
 }
#include
using namespace std;
 
int main ()
{
   // Local variable declaration:
   int num = 10;
 
   // do loop execution
   do
   {
       cout << "value of number: " << num << endl;
       num=num+ 1;
       if( num > 15)
       {
          // terminate the loop
          break;
       }
   }while( num < 20 );
 
   return 0;
}
//program to show how exception handling work
 
#include 
using namespace std;
 
//method definition
double divisionby(int num1, int num2)
{
    if( num2 == 0 )
    {
        throw "Division by zero condition!";
    }
    cout<<"answer = ";
    return (num1/num2);
}
 
int main ()
{
    //variable declaration
    int n1,n2;
 
    //take user input
    cout<<"enter two numbers for division operation  :  ";
    cin>>n1>>n2;
    double n3 = 0;
 
    //try catch to handle run time error
    try
    {
        n3 = divisionby(n1, n2);
        cout << n3 << endl;
    }
    catch (const char* msg)
    {
        //it will display error msg
        cout << msg << endl;
    }
 
   return 0;
}
//id-16776
#include 
using namespace std;
 
double divisionby(int num1, int num2)
{
   if( num2 == 0 )
   {
      throw "Division by zero condition!";
   }
   cout<<"answer = ";
   return (num1/num2);
}
 
int main ()
{
   int n1,n2;
   cout<<"enter two numbers for division operation  :  ";
   cin>>n1>>n2;
   double n3 = 0;
 
//try catch to handle run time error
    try
       {
         n3 = divisionby(n1, n2);
         cout << n3 << endl;
       }
    catch (const char* msg)
        {
            //it will display error msg
         cout << msg << endl;
        }
 
   return 0;
}
#include

#include<conio.h>

#include

#include<stdlib.h>

#include<ctype.h>

#include

using namespace std;

 

int main( )

{

    //variable declaration

  ofstream outfile;

  ifstream  infile;

  char fname1[10],fname2[20];

  char ch,uch;

 

    //user Input

  cout<<"Enter a file name to be copied ";

  cin>> fname1;

  cout<<"Enter new file name";

  cin>>fname2;

  infile.open(fname1);

 

    if( infile.fail( ) )

        {

            cerr<< " No such a file Exit";

            getch();

            exit(1);

        }

  outfile.open( fname2);

    if(outfile.fail( ))

    {

      cerr<<"Unable to create a file";

      getch();

      exit(1);

    }

  while( !infile.eof( ) )

  {

    ch = (char) infile.get( );

    uch = toupper(ch);

    outfile.put(uch);

  }

  infile.close( );

  outfile.close( );

 

}

OUTPUT

Enter a file name to be copied : old.txt Enter new file name : new.txt

#include

#include

using namespace std;

 

int main ()

{

 

    //variable declaration

    int number;

 

    //take input for number from user

    cout<<"Enter number : ";

    cin>>number;

 

    //use of sqrt function to find square root

    cout << "square root of " << number << " is " << sqrt(number);

 

    cout<<"\n\n";

 

    //use of cbrt function to find cube root

    cout << "cube root of " << number << " is " << cbrt(number);

 

    cout<<"\n";

}

OUTPUT

Enter number : 27 square root of 27 is 5.19615 cube root of 27 is 3
#include 
#include 
using namespace std;
 
int main ()
{
 
    //variable declaration
    int number;
 
    //take input for number from user
    cout<<"Enter number : ";
    cin>>number;
 
    //use of sqrt function to find square root
    cout << "square root of " << number << " is " << sqrt(number);
 
    cout<<"\n\n";
 
    //use of cbrt function to find cube root
    cout << "cube root of " << number << " is " << cbrt(number);
 
    cout<<"\n";
}
#include <stdio.h>
#include <math.h>
#include
 
using namespace std;
 
int main()
{
    int num, tempnum;
 
    cout<<"Enter a number: ";
    cin>>num;
 
    tempnum = sqrt(num);
 
    if(tempnum*tempnum==num)
    {
       cout<<"YES,its perfect square of : "<<sqrt(num);
    }
 
    else
    {
        cout<<"NO,its not perfect square";
    }
 
    return 0;
}

#include 
#include 
 
using namespace std;
 
int main()
{
    //Vector to store integers
    vector vex;
    cout<<"added value in vector  :\n";
 
    //add value in vector
    vex.push_back(130);
    vex.push_back(500);
    vex.push_back(353);
 
    for(int x=0; x<vex.size(); x++)
        {
            //Should output 130 500 353
            cout<<vex[x]<<" ";
        }
 
    //Checks if empty
    if(!vex.empty())
        {
            //Clears vector
            vex.clear();
        }
 
    vector another_vector;
    another_vector.push_back(10);
    vex.push_back(10);
 
    if(vex==another_vector)
        {
            vex.push_back(20);
        }
 
    for(int y=0; y<vex.size(); y++)
        {
            //Should output 10 20
            cout<<vex[y]<<" ";
        }
    return 0;
}
